name: wheels
on:
  push:

jobs:
  launcher:
    name: Build Windows launchers
    runs-on: windows-latest
    steps:
    - name: Clone distlib
      run: git clone https://github.com/pypa/distlib.git

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Build
      run: |
        cd distlib/PC
        mkdir build

        echo 'cmake_minimum_required(VERSION 3.15)

        project(simple_launcher LANGUAGES C)

        add_executable(simple_launcher_cli launcher.c)
        target_link_libraries(simple_launcher_cli shlwapi.lib)
        target_compile_definitions(simple_launcher_cli PUBLIC -D_CONSOLE)

        add_executable(simple_launcher_gui WIN32 launcher.c)
        target_link_libraries(simple_launcher_gui shlwapi.lib)' | Out-File CMakeLists.txt

        cd build
        $env:VERBOSE="1"

        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
        cmake --build .

        mv simple_launcher_cli.exe t64.exe
        mv simple_launcher_gui.exe w64.exe

    - name: Upload launchers
      uses: actions/upload-artifact@v3
      with:
        name: launchers
        path: 'distlib/PC/build/*.exe'
